version: '2'
services:
    accountsrb-mysql:
        container_name: accountsrb-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/accountsrb/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=admin123
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=accountsrb
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
